name: clean_architecture
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  google_fonts: ^4.0.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  another_flushbar: ^1.12.30
  dio_logging_interceptor: ^1.0.1
  dio: ^4.0.6
  drift: ^2.8.0
  path_provider: ^2.0.15
  path: ^1.8.2
  json_annotation: ^4.8.1
  hive: ^2.2.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  lottie: ^2.3.2
  animated_gradient: ^0.0.2
  hive_flutter: ^1.1.0
  overlay_support: ^2.1.0
  go_router: ^10.0.0
  super_rich_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  drift_dev: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/lottie/
     - assets/lang/
     - assets/color/

flutter_gen:
  output: lib/common/assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
  assets:
    enabled: true
  colors:
    inputs:
      - assets/color/colors.xml
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
